### ISSUE TITLE
Absolute paths in tar tests

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#1011]
There are some absolute paths in the tar tests. @AnnikaH 

**util/integration/tar:**
[1](https://github.com/hioa-cs/IncludeOS/blob/dev/test/util/integration/tar/service.cpp#L68)
[2](https://github.com/hioa-cs/IncludeOS/blob/dev/test/util/integration/tar/service.cpp#L75)

**util/integration/tar_gz**
[3](https://github.com/hioa-cs/IncludeOS/blob/dev/test/util/integration/tar_gz/service.cpp#L68)
[4](https://github.com/hioa-cs/IncludeOS/blob/dev/test/util/integration/tar_gz/service.cpp#L75)

When changing the file path the tar_gz test works, but I can't get the tar test to work. It results in the following error:

```
<vm> home/ubuntu/IncludeOS/test/util/integration/tar/tar_example/l1_f1/l2/README.md - element
num_elements after increment:  9
<vm> home/ubuntu/IncludeOS/test/util/integration/tar/tar_example/l1_f1/service.cpp - element
num_elements after increment:  10
<vm>
<vm> 	**** PANIC: ****
* <qemu>:  Stopping test_tar.img PID 6710
* <qemu>:   + child process  6711
* <qemu>:  process signalled
* <VMRunner>:  VM stopped
* <VMRunner>:  Cancelling timer
* <VMRunner>:  Exited with status 67 ( VM_FAIL )
* <VMRunner>:  Calling on_exit

[ FAIL ] <VMRunner> terminating with uncaught exception of type tar::Tar_exception: Path /home/ubuntu/IncludeOS/test/util/integration/tar/tar_example/l1_f1/l2/ doesn't exist. Folder names should have a trailing /
```

The util test folder is not actually run at the moment as a PR test. I'll see to that.

**Comment by AnnikaH** [comment]
Will have a look at it!

**Comment by mnordsletten** [comment]
Great. I won't enable the util PR test before this is fixed :) Let me know.

**Comment by AndreasAakesson** [comment]
@mnordsletten this is solved. Just close this when you have enabled it!

**Comment by mnordsletten** [comment]
This is not solved. There are still absolute paths in the tests. 
```const std::string path1 = "home/annikaha/IncludeOS/test/util/integration/tar/tar_example/l1_f1/l2/README.md";```

**Comment by AnnikaH** [comment]
Fixed in PR #1108

**Comment by mnordsletten** [comment]
I will check this and enable the util test in jenkins if it works :)

**Comment by AnnikaH** [comment]
👍
